-- =============================================================================
-- Migración: rol "Lector" y apartado "Consultas" (solo lectura)
-- Fecha: 2026-08-10
-- Ejecución: MANUAL. Correr en el Postgres de producción.
--
-- Objetivo: un rol que solo pueda MIRAR los pedidos y las ventas de las tiendas
-- que tenga asignadas, sin poder crear, editar, cambiar de estado, cobrar ni
-- eliminar nada. Puede listar, ver el detalle y exportar a PDF (individual y
-- masivo, igual que hoy en Pedidos).
--
-- Pantallas nuevas en el front (apartado "Consultas" del menú lateral):
--   /consultas/pedidos            listado de pedidos, con selector de tienda
--   /consultas/pedidos/view/:id   detalle del pedido (solo ver + PDF)
--   /consultas/ventas             listado de ventas, con selector de tienda
--   /consultas/ventas/view/:id    detalle de la venta (solo ver + PDF)
--
-- Enfoque 100% aditivo: NO crea ni modifica tablas, queries ni procedures.
-- Las pantallas reutilizan los endpoints que ya existen:
--   /retrieveEstablishments, /listProductForSaleStoreOrder,
--   /getProductForSaleStoreOrder, /listShopSaleV3, /getShopSale...
-- Esta migración solo toca la tabla "role" (una fila nueva + paths de admin).
--
-- ASIGNACIÓN DE TIENDAS: igual que en "Listado de Tiendas" — el usuario ve solo
-- las tiendas que llevan su correo en establishment.description. El admin
-- (role_id = 1) las ve todas sin necesidad de estar asignado. No hay cambio de
-- esquema aquí; es la misma convención que ya se usa.
--
-- ORDEN DE EJECUCIÓN (una sola corrida, ANTES de desplegar el front nuevo):
--   PASO 0 -> Revisar el estado actual de los roles
--   PASO 1 -> Crear el rol "Lector"
--   PASO 2 -> Dar acceso a /consultas a los roles que ya existen (admin)
-- =============================================================================


-- #############################################################################
-- PASO 0 — Revisar antes de tocar nada
--
-- El guard canActivateV2 valida la ruta contra role.paths, que es un JSON con
-- objetos { "matchPattern": "<regex>" }. Correr esto primero para ver con qué
-- forma exacta están guardados los paths de cada rol y cuál es el id máximo:
--
--   SELECT id, "name", status, paths FROM "role" ORDER BY id;
--
-- OJO con "^\\/home$": el guard, cuando la ruta pedida no está en paths,
-- redirige a /home — y /home también pasa por el guard. Si el rol no tiene
-- /home entre sus paths, la redirección se queda dando vueltas. Por eso el
-- rol nuevo lo incluye.
-- #############################################################################


-- #############################################################################
-- PASO 1 — Rol "Lector"
--
-- status = 1 (activo), igual que el resto de roles.
-- El id se genera solo (la columna es GENERATED BY DEFAULT AS IDENTITY).
-- #############################################################################

INSERT INTO "role" ("name", status, paths)
SELECT 'Lector', 1, '[
    {"matchPattern": "^\\/home$"},
    {"matchPattern": "^\\/consultas\\/pedidos(\\/.*)?$"},
    {"matchPattern": "^\\/consultas\\/ventas(\\/.*)?$"}
]'::jsonb::text
WHERE NOT EXISTS (SELECT 1 FROM "role" WHERE "name" = 'Lector');

-- Anotar el id que quedó — es el que se elige al crear/editar un usuario:
--   SELECT id, "name", paths FROM "role" WHERE "name" = 'Lector';


-- #############################################################################
-- PASO 2 — Acceso al apartado para los roles que ya existen
--
-- Sin esto, el admin no ve "Consultas" en el menú (getUserMenuItems filtra los
-- ítems contra paths) y entrar por URL lo manda a /home.
--
-- Solo agrega el patrón si el rol todavía no lo tiene, así se puede correr
-- más de una vez sin duplicarlo.
--
-- Ajustar el IN (...) si algún otro rol también debe ver el apartado.
-- #############################################################################

UPDATE "role"
SET paths = (
    paths::jsonb || '[{"matchPattern": "^\\/consultas(\\/.*)?$"}]'::jsonb
)::text
WHERE id IN (1)
  AND NOT paths::jsonb @> '[{"matchPattern": "^\\/consultas(\\/.*)?$"}]'::jsonb;


-- #############################################################################
-- VERIFICACIÓN
-- #############################################################################
--
-- 1) El rol existe y sus paths están bien formados:
--      SELECT id, "name", jsonb_pretty(paths::jsonb) FROM "role" WHERE "name" = 'Lector';
--
-- 2) El regex hace match con las rutas reales (los 4 deben dar true):
--      SELECT '/consultas/pedidos'          ~ '^\/consultas\/pedidos(\/.*)?$',
--             '/consultas/pedidos/view/abc' ~ '^\/consultas\/pedidos(\/.*)?$',
--             '/consultas/ventas'           ~ '^\/consultas\/ventas(\/.*)?$',
--             '/consultas/ventas/view/abc'  ~ '^\/consultas\/ventas(\/.*)?$';
--
-- 3) Y NO hace match con lo que el lector no debe abrir (los 3 deben dar false):
--      SELECT '/productsForSale/order' ~ '^\/consultas\/pedidos(\/.*)?$',
--             '/store/sales/create'    ~ '^\/consultas\/ventas(\/.*)?$',
--             '/establishments'        ~ '^\/consultas\/(pedidos|ventas)(\/.*)?$';
--
-- 4) El admin quedó con el patrón nuevo:
--      SELECT id, "name" FROM "role"
--       WHERE paths::jsonb @> '[{"matchPattern": "^\\/consultas(\\/.*)?$"}]'::jsonb;
--
-- 5) Para probar de punta a punta: crear un usuario con rol Lector y escribir su
--    correo en la descripción de una tienda (Sistema > Tiendas > Editar).
--    Al entrar debe ver solo "Consultas" en el menú y, dentro, solo esa tienda.
--
-- NOTA: los paths viajan dentro del JWT. Un usuario que ya tenga sesión abierta
-- debe volver a iniciar sesión para que le lleguen los permisos nuevos.
-- #############################################################################
