-- public.action_type definition

-- Drop table

-- DROP TABLE action_type;

CREATE TABLE action_type ( id int4 DEFAULT nextval('action_type_at_id_seq'::regclass) NOT NULL, status int2 NOT NULL, "name" varchar(50) NOT NULL, "type" varchar(30) NOT NULL, unit_name varchar(30) NULL, color varchar(7) NULL, "action" varchar(10) NULL, CONSTRAINT action_type_pkey PRIMARY KEY (id));


-- public.establishment_type definition

-- Drop table

-- DROP TABLE establishment_type;

CREATE TABLE establishment_type ( id int4 NOT NULL, "name" varchar(50) NOT NULL, CONSTRAINT establishment_type_pkey PRIMARY KEY (id));


-- public.finished_product_type definition

-- Drop table

-- DROP TABLE finished_product_type;

CREATE TABLE finished_product_type ( id int4 NOT NULL, "name" varchar(50) NOT NULL, CONSTRAINT finished_product_type_pkey PRIMARY KEY (id));


-- public.payment_type definition

-- Drop table

-- DROP TABLE payment_type;

CREATE TABLE payment_type ( id int4 DEFAULT nextval('payment_type_pt_id_seq'::regclass) NOT NULL, status int2 NOT NULL, "name" varchar(30) NOT NULL, CONSTRAINT payment_type_pkey PRIMARY KEY (id));


-- public.raw_material_by_provider_type definition

-- Drop table

-- DROP TABLE raw_material_by_provider_type;

CREATE TABLE raw_material_by_provider_type ( id int4 NOT NULL, "name" varchar(50) NOT NULL, CONSTRAINT raw_material_by_provider_type_pkey PRIMARY KEY (id));


-- public."role" definition

-- Drop table

-- DROP TABLE "role";

CREATE TABLE "role" ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, status int2 NOT NULL, "name" varchar(30) NOT NULL, paths text NULL, CONSTRAINT role_pkey PRIMARY KEY (id));


-- public.sql_queries definition

-- Drop table

-- DROP TABLE sql_queries;

CREATE TABLE sql_queries ( id serial4 NOT NULL, descripcion varchar(500) NULL, "path" varchar(100) NULL, consulta_sql text NULL, principal_table varchar(100) NULL, "type" varchar(50) NULL, CONSTRAINT sql_queries_pkey PRIMARY KEY (id));


-- public.status definition

-- Drop table

-- DROP TABLE status;

CREATE TABLE status ( id serial4 NOT NULL, status int2 NOT NULL, "name" varchar(30) NOT NULL, "type" varchar(25) NOT NULL, bg_color varchar(7) NULL, color varchar(7) NULL, CONSTRAINT status_pkey PRIMARY KEY (id));


-- public.unit_base definition

-- Drop table

-- DROP TABLE unit_base;

CREATE TABLE unit_base ( id serial4 NOT NULL, "name" varchar(30) NOT NULL, "type" varchar(10) NOT NULL, CONSTRAINT unit_base_pkey PRIMARY KEY (id));


-- public.measure definition

-- Drop table

-- DROP TABLE measure;

CREATE TABLE measure ( id serial4 NOT NULL, status int2 NOT NULL, "name" varchar(30) NOT NULL, unit_base_id int4 NULL, unit_base_quantity numeric(8, 5) NOT NULL, CONSTRAINT measure_pkey PRIMARY KEY (id), CONSTRAINT measure_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES unit_base(id));


-- public."user" definition

-- Drop table

-- DROP TABLE "user";

CREATE TABLE "user" ( id uuid DEFAULT gen_random_uuid() NOT NULL, username varchar(50) NOT NULL, "password" varchar(255) NULL, status_id int4 NOT NULL, email varchar(50) NOT NULL, phone int4 NULL, role_id int4 NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NULL, updated_date timestamp NULL, external_id varchar(30) NULL, CONSTRAINT user_email_key UNIQUE (email), CONSTRAINT user_pkey PRIMARY KEY (id), CONSTRAINT user_fk_role_id FOREIGN KEY (role_id) REFERENCES "role"(id), CONSTRAINT user_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.establishment definition

-- Drop table

-- DROP TABLE establishment;

CREATE TABLE establishment ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NOT NULL, address varchar(50) NOT NULL, description text NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, receive_pending_orders_enabled bool DEFAULT false NOT NULL, establishment_type_id int4 DEFAULT 1 NOT NULL, CONSTRAINT establishment_pkey PRIMARY KEY (id), CONSTRAINT establishment_establishment_type_fk FOREIGN KEY (establishment_type_id) REFERENCES establishment_type(id), CONSTRAINT finished_product_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT finished_product_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.finished_product definition

-- Drop table

-- DROP TABLE finished_product;

CREATE TABLE finished_product ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NOT NULL, description varchar(200) NULL, photo text NULL, thumb text NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, unit_base_id int4 NOT NULL, finished_product_type_id int4 DEFAULT 1 NOT NULL, sort_order int4 NULL, CONSTRAINT finished_product_pkey PRIMARY KEY (id), CONSTRAINT finished_product_finished_product_type_fk FOREIGN KEY (finished_product_type_id) REFERENCES finished_product_type(id), CONSTRAINT finished_product_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT finished_product_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id), CONSTRAINT finished_product_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES unit_base(id));


-- public.inventory definition

-- Drop table

-- DROP TABLE inventory;

CREATE TABLE inventory ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(150) NOT NULL, description varchar(50) NULL, person_in_charge_id uuid NOT NULL, inventory_type varchar(25) NOT NULL, unit_name varchar(150) NOT NULL, status_id int4 DEFAULT 48 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, CONSTRAINT inventory_pkey PRIMARY KEY (id), CONSTRAINT inventory_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT inventory_fk_person_in_charge_id FOREIGN KEY (person_in_charge_id) REFERENCES "user"(id), CONSTRAINT inventory_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.inventory_element definition

-- Drop table

-- DROP TABLE inventory_element;

CREATE TABLE inventory_element ( id int4 DEFAULT nextval('inventory_element_ie_id_seq'::regclass) NOT NULL, inventory_id uuid NOT NULL, element_type varchar(20) NOT NULL, element_table varchar(100) NOT NULL, establishment_id uuid NULL, measure_id int4 NULL, quantity numeric(12, 2) NOT NULL, status_id int4 DEFAULT 48 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, element_fk uuid NOT NULL, CONSTRAINT inventory_element_pkey PRIMARY KEY (id), CONSTRAINT inventory_element_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT inventory_element_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT inventory_element_fk_inventory_id FOREIGN KEY (inventory_id) REFERENCES inventory(id), CONSTRAINT inventory_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT inventory_element_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.inventory_element_action definition

-- Drop table

-- DROP TABLE inventory_element_action;

CREATE TABLE inventory_element_action ( id int4 DEFAULT nextval('inventory_element_action_iem_id_seq'::regclass) NOT NULL, "comment" varchar(255) NULL, source_inventory_element_id int4 NOT NULL, target_inventory_element_id int4 NULL, quantity numeric(12, 5) NOT NULL, measure_id int4 NOT NULL, action_type_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT inventory_element_action_pkey PRIMARY KEY (id), CONSTRAINT inventory_element_action_fk_action_type_id FOREIGN KEY (action_type_id) REFERENCES action_type(id), CONSTRAINT inventory_element_action_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT inventory_element_action_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT inventory_element_action_fk_source_inventory_element_id FOREIGN KEY (source_inventory_element_id) REFERENCES inventory_element(id), CONSTRAINT inventory_element_action_fk_target_inventory_element_id FOREIGN KEY (target_inventory_element_id) REFERENCES inventory_element(id));


-- public.product_for_sale definition

-- Drop table

-- DROP TABLE product_for_sale;

CREATE TABLE product_for_sale ( id uuid DEFAULT gen_random_uuid() NOT NULL, price numeric(10, 2) NOT NULL, establishment_id uuid NOT NULL, finished_product_id uuid NOT NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, sort_order int4 NULL, CONSTRAINT product_for_sale_pkey PRIMARY KEY (id), CONSTRAINT product_for_sale_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT product_for_sale_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT product_for_sale_fk_finished_product_id FOREIGN KEY (finished_product_id) REFERENCES finished_product(id), CONSTRAINT product_for_sale_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.product_for_sale_store_order definition

-- Drop table

-- DROP TABLE product_for_sale_store_order;

CREATE TABLE product_for_sale_store_order ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NULL, "comment" text NULL, establishment_id uuid NOT NULL, inventory_id uuid NULL, final_amount numeric(10, 2) NOT NULL, factory_status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, store_status_id int4 NOT NULL, CONSTRAINT product_for_sale_store_order_pkey PRIMARY KEY (id), CONSTRAINT product_for_sale_store_order_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT product_for_sale_store_order_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT product_for_sale_store_order_fk_factory_status_id FOREIGN KEY (factory_status_id) REFERENCES status(id), CONSTRAINT product_for_sale_store_order_fk_inventory_id FOREIGN KEY (inventory_id) REFERENCES inventory(id), CONSTRAINT product_for_sale_store_order_status_fk FOREIGN KEY (store_status_id) REFERENCES status(id));


-- public.product_for_sale_store_order_element definition

-- Drop table

-- DROP TABLE product_for_sale_store_order_element;

CREATE TABLE product_for_sale_store_order_element ( id int4 DEFAULT nextval('product_for_sale_store_order_element_pfssoe_id_seq'::regclass) NOT NULL, product_for_sale_id uuid NOT NULL, quantity numeric(12, 5) NOT NULL, measure_id int4 NOT NULL, price numeric(10, 2) NOT NULL, total_price numeric(10, 2) NOT NULL, "date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, pfsso_id uuid NOT NULL, CONSTRAINT product_for_sale_store_order_element_pkey PRIMARY KEY (id), CONSTRAINT product_for_sale_store_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT product_for_sale_store_order_element_fk_product_for_sale_id FOREIGN KEY (product_for_sale_id) REFERENCES product_for_sale(id), CONSTRAINT product_for_sale_store_order_element_product_for_sale_store_ord FOREIGN KEY (pfsso_id) REFERENCES product_for_sale_store_order(id));


-- public.provider definition

-- Drop table

-- DROP TABLE provider;

CREATE TABLE provider ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NOT NULL, phone int4 NULL, description varchar(255) NULL, company varchar(50) NOT NULL, email varchar(100) NOT NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, CONSTRAINT provider_email_key UNIQUE (email), CONSTRAINT provider_pkey PRIMARY KEY (id), CONSTRAINT provider_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT provider_fk_sttus_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.raw_material definition

-- Drop table

-- DROP TABLE raw_material;

CREATE TABLE raw_material ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NOT NULL, description varchar(255) NULL, photo text NULL, thumb text NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, unit_base_id int4 NOT NULL, sort_order int4 NULL, CONSTRAINT raw_material_pkey PRIMARY KEY (id), CONSTRAINT raw_material_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT raw_material_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id), CONSTRAINT raw_material_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES unit_base(id));


-- public.raw_material_by_provider definition

-- Drop table

-- DROP TABLE raw_material_by_provider;

CREATE TABLE raw_material_by_provider ( id uuid DEFAULT gen_random_uuid() NOT NULL, price numeric(10, 2) NOT NULL, provider_id uuid NOT NULL, raw_material_base_id uuid NOT NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, raw_material_by_provider_type_id int4 DEFAULT 1 NOT NULL, sort_order int4 NULL, CONSTRAINT raw_material_by_provider_pkey PRIMARY KEY (id), CONSTRAINT raw_material_by_provider_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT raw_material_by_provider_fk_provider_id FOREIGN KEY (provider_id) REFERENCES provider(id), CONSTRAINT raw_material_by_provider_fk_raw_material_base_id FOREIGN KEY (raw_material_base_id) REFERENCES raw_material(id), CONSTRAINT raw_material_by_provider_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id), CONSTRAINT raw_material_by_provider_fk_type_id FOREIGN KEY (raw_material_by_provider_type_id) REFERENCES raw_material_by_provider_type(id));


-- public.raw_material_order definition

-- Drop table

-- DROP TABLE raw_material_order;

CREATE TABLE raw_material_order ( id uuid DEFAULT gen_random_uuid() NOT NULL, "name" varchar(50) NOT NULL, description varchar(100) NULL, provider_id uuid NOT NULL, payment_type_id int4 NOT NULL, pending_amount numeric(10, 2) NOT NULL, paid_amount numeric(10, 2) NOT NULL, final_amount numeric(10, 2) NOT NULL, payment_status_id int4 NOT NULL, status_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, raw_material_by_provider_type_id int4 DEFAULT 1 NOT NULL, CONSTRAINT raw_material_order_pkey PRIMARY KEY (id), CONSTRAINT raw_material_order_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT raw_material_order_fk_payment_status_id FOREIGN KEY (payment_status_id) REFERENCES status(id), CONSTRAINT raw_material_order_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES payment_type(id), CONSTRAINT raw_material_order_fk_provider_id FOREIGN KEY (provider_id) REFERENCES provider(id), CONSTRAINT raw_material_order_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id), CONSTRAINT raw_material_order_raw_material_by_provider_type_fk FOREIGN KEY (raw_material_by_provider_type_id) REFERENCES raw_material_by_provider_type(id));


-- public.raw_material_order_element definition

-- Drop table

-- DROP TABLE raw_material_order_element;

CREATE TABLE raw_material_order_element ( id int4 DEFAULT nextval('raw_material_order_element_pmoe_id_seq'::regclass) NOT NULL, raw_material_order_id uuid NOT NULL, raw_material_by_provider_id uuid NOT NULL, quantity numeric(12, 5) NOT NULL, discount numeric(10, 2) NOT NULL, measure_id int4 NOT NULL, price numeric(10, 2) NOT NULL, subtotal_price numeric(10, 2) NOT NULL, total_discount numeric(10, 2) NOT NULL, total_price numeric(10, 2) NOT NULL, "date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT raw_material_order_element_pkey PRIMARY KEY (id), CONSTRAINT raw_material_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT raw_material_order_element_fk_raw_material_by_provider_id FOREIGN KEY (raw_material_by_provider_id) REFERENCES raw_material_by_provider(id), CONSTRAINT raw_material_order_element_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES raw_material_order(id));


-- public.raw_material_order_element_aux definition

-- Drop table

-- DROP TABLE raw_material_order_element_aux;

CREATE TABLE raw_material_order_element_aux ( id int4 DEFAULT nextval('raw_material_order_element_aux_pmoe_id_seq'::regclass) NOT NULL, raw_material_order_id uuid NOT NULL, raw_material_by_provider_id uuid NOT NULL, quantity numeric(8, 5) NOT NULL, discount numeric(10, 2) NOT NULL, measure_id int4 NOT NULL, price numeric(10, 2) NOT NULL, subtotal_price numeric(10, 2) NOT NULL, total_discount numeric(10, 2) NOT NULL, total_price numeric(10, 2) NOT NULL, "date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT raw_material_order_element_aux_pkey PRIMARY KEY (id), CONSTRAINT raw_material_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT raw_material_order_element_fk_raw_material_by_provider_id FOREIGN KEY (raw_material_by_provider_id) REFERENCES raw_material_by_provider(id), CONSTRAINT raw_material_order_element_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES raw_material_order(id));


-- public.raw_material_order_payment definition

-- Drop table

-- DROP TABLE raw_material_order_payment;

CREATE TABLE raw_material_order_payment ( id int4 DEFAULT nextval('raw_material_order_payment_pmop_id_seq'::regclass) NOT NULL, raw_material_order_id uuid NOT NULL, amount numeric(10, 2) NOT NULL, payment_type_id int4 NOT NULL, "date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT raw_material_order_payment_pkey PRIMARY KEY (id), CONSTRAINT raw_material_order_payment_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES payment_type(id), CONSTRAINT raw_material_order_payment_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES raw_material_order(id));


-- public.shop_sale definition

-- Drop table

-- DROP TABLE shop_sale;

CREATE TABLE shop_sale ( id uuid DEFAULT gen_random_uuid() NOT NULL, name_client varchar(50) NOT NULL, nota varchar(100) NOT NULL, delivery numeric(10, 2) DEFAULT 0 NULL, nit_client varchar(10) DEFAULT 'CF'::character varying NULL, establishment_id uuid NOT NULL, status_id int4 NOT NULL, total numeric(10, 2) NOT NULL, total_discount numeric(10, 2) NOT NULL, payment_type_id int4 NOT NULL, creator_user_id uuid NOT NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, CONSTRAINT shop_sale_pkey PRIMARY KEY (id), CONSTRAINT shop_sale_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT shop_sale_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT shop_sale_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES payment_type(id), CONSTRAINT shop_sale_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.shop_sale_element definition

-- Drop table

-- DROP TABLE shop_sale_element;

CREATE TABLE shop_sale_element ( id int4 DEFAULT nextval('shop_sale_element_sse_id_seq'::regclass) NOT NULL, shop_sale_id uuid NOT NULL, product_for_sale_id uuid NOT NULL, price numeric(10, 2) NOT NULL, subtotal numeric(10, 2) NOT NULL, total numeric(10, 2) NOT NULL, discount numeric(10, 2) NOT NULL, total_discount numeric(10, 2) NOT NULL, quantity numeric(12, 5) NOT NULL, measure_id int4 NULL, CONSTRAINT shop_sale_element_pkey PRIMARY KEY (id), CONSTRAINT shop_sale_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES measure(id), CONSTRAINT shop_sale_element_fk_product_for_sale_id FOREIGN KEY (product_for_sale_id) REFERENCES product_for_sale(id), CONSTRAINT shop_sale_element_fk_shop_sale_id FOREIGN KEY (shop_sale_id) REFERENCES shop_sale(id));


-- public.store_expense definition

-- Drop table

-- DROP TABLE store_expense;

CREATE TABLE store_expense ( id uuid DEFAULT gen_random_uuid() NOT NULL, title varchar(40) NOT NULL, "comment" varchar(100) NULL, total_amount numeric(10, 2) DEFAULT 0.00 NOT NULL, nit varchar(10) DEFAULT 'C/F'::character varying NOT NULL, supplier varchar(20) NULL, establishment_id uuid NOT NULL, status_id int4 NOT NULL, creator_user_id uuid NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT store_expense_pkey PRIMARY KEY (id), CONSTRAINT store_expense_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES "user"(id), CONSTRAINT store_expense_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT store_expense_fk_status_id FOREIGN KEY (status_id) REFERENCES status(id));


-- public.cash_closing definition

-- Drop table

-- DROP TABLE cash_closing;

CREATE TABLE cash_closing ( id uuid DEFAULT gen_random_uuid() NOT NULL, establishment_id uuid NOT NULL, status_id int4 NOT NULL, shop_sales jsonb NULL, last_inventory_capture jsonb NULL, last_inventory_creation_date timestamp NULL, inventory_capture jsonb NULL, inventory_element_actions jsonb NULL, validator_user uuid NOT NULL, confirm_user uuid NULL, creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, updated_date timestamp NULL, note text NULL, sale_store_orders jsonb NULL, CONSTRAINT cash_closing_pkey PRIMARY KEY (id), CONSTRAINT cash_closing_fk_confirm_user FOREIGN KEY (confirm_user) REFERENCES "user"(id), CONSTRAINT cash_closing_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES establishment(id), CONSTRAINT cash_closing_fk_sttus_id FOREIGN KEY (status_id) REFERENCES status(id), CONSTRAINT cash_closing_fk_validator_user FOREIGN KEY (validator_user) REFERENCES "user"(id));


-- ============================================================
-- MIGRATION: shop_sale credit payment support
-- ============================================================

-- Add payment type "Crédito"
INSERT INTO payment_type (status, "name") SELECT 1, 'Crédito' WHERE NOT EXISTS (SELECT 1 FROM payment_type WHERE "name" = 'Crédito');

-- Add payment-tracking columns to shop_sale (default 5 = Pagado, so existing rows keep Pagado status)
ALTER TABLE shop_sale
    ADD COLUMN IF NOT EXISTS paid_amount numeric(10,2) DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS pending_amount numeric(10,2) DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS payment_status_id int4 DEFAULT 5 NOT NULL;

ALTER TABLE shop_sale
    DROP CONSTRAINT IF EXISTS shop_sale_fk_payment_status_id;

ALTER TABLE shop_sale
    ADD CONSTRAINT shop_sale_fk_payment_status_id FOREIGN KEY (payment_status_id) REFERENCES status(id);


-- public.shop_sale_payment definition

CREATE SEQUENCE IF NOT EXISTS shop_sale_payment_id_seq;

CREATE TABLE IF NOT EXISTS shop_sale_payment ( id int4 DEFAULT nextval('shop_sale_payment_id_seq'::regclass) NOT NULL, shop_sale_id uuid NOT NULL, amount numeric(10, 2) NOT NULL, payment_type_id int4 NOT NULL, "date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL, CONSTRAINT shop_sale_payment_pkey PRIMARY KEY (id), CONSTRAINT shop_sale_payment_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES payment_type(id), CONSTRAINT shop_sale_payment_fk_shop_sale_id FOREIGN KEY (shop_sale_id) REFERENCES shop_sale(id));

-- Saldo de créditos por período de cierre
ALTER TABLE cash_closing ADD COLUMN IF NOT EXISTS credit_balance numeric(10,2) DEFAULT 0 NOT NULL;
-- Sobrante de caja ingresado manualmente al cierre
ALTER TABLE cash_closing ADD COLUMN IF NOT EXISTS sobrante numeric(10,2) DEFAULT 0 NOT NULL;

-- ============================================================
-- MIGRATION: separar pago de pedido y pago de envío
-- El pago del pedido (subtotal) se rastrea con paid_amount/pending_amount.
-- El pago del envío se rastrea con las nuevas columnas delivery_*.
-- ============================================================

-- Tipo de pago del envío + tracking de crédito del envío (default 5 = Pagado)
ALTER TABLE shop_sale
    ADD COLUMN IF NOT EXISTS delivery_payment_type_id int4 NULL,
    ADD COLUMN IF NOT EXISTS delivery_paid_amount numeric(10,2) DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS delivery_pending_amount numeric(10,2) DEFAULT 0 NOT NULL,
    ADD COLUMN IF NOT EXISTS delivery_payment_status_id int4 DEFAULT 5 NOT NULL;

ALTER TABLE shop_sale
    DROP CONSTRAINT IF EXISTS shop_sale_fk_delivery_payment_type_id;
ALTER TABLE shop_sale
    ADD CONSTRAINT shop_sale_fk_delivery_payment_type_id FOREIGN KEY (delivery_payment_type_id) REFERENCES payment_type(id);

ALTER TABLE shop_sale
    DROP CONSTRAINT IF EXISTS shop_sale_fk_delivery_payment_status_id;
ALTER TABLE shop_sale
    ADD CONSTRAINT shop_sale_fk_delivery_payment_status_id FOREIGN KEY (delivery_payment_status_id) REFERENCES status(id);

-- Discriminador en el historial de pagos: 'ORDER' (pedido) o 'DELIVERY' (envío)
ALTER TABLE shop_sale_payment
    ADD COLUMN IF NOT EXISTS payment_target varchar(10) DEFAULT 'ORDER' NOT NULL;

-- ============================================================
-- MIGRATION: número de venta visible (correlativo POR TIENDA)
-- Cada establecimiento lleva su propia numeración 1, 2, 3...
-- Se asigna automáticamente vía trigger BEFORE INSERT (atómico).
-- Numera también las ventas existentes en orden cronológico.
-- ============================================================
ALTER TABLE shop_sale ADD COLUMN IF NOT EXISTS sale_number bigint;

-- Contador atómico por establecimiento
CREATE TABLE IF NOT EXISTS shop_sale_counter (
    establishment_id uuid PRIMARY KEY REFERENCES establishment(id),
    last_number bigint NOT NULL DEFAULT 0
);

-- Backfill cronológico por tienda (solo las ventas que aún no tienen número)
WITH base AS (
    SELECT establishment_id, COALESCE(max(sale_number), 0) AS mx
    FROM shop_sale
    GROUP BY establishment_id
),
ordered AS (
    SELECT id, establishment_id,
           row_number() OVER (PARTITION BY establishment_id ORDER BY creation_date, id) AS rn
    FROM shop_sale
    WHERE sale_number IS NULL
)
UPDATE shop_sale ss
SET sale_number = o.rn + b.mx
FROM ordered o
JOIN base b ON b.establishment_id = o.establishment_id
WHERE ss.id = o.id;

-- Inicializar los contadores con el máximo actual por tienda
INSERT INTO shop_sale_counter (establishment_id, last_number)
SELECT establishment_id, max(sale_number)
FROM shop_sale
WHERE sale_number IS NOT NULL
GROUP BY establishment_id
ON CONFLICT (establishment_id)
DO UPDATE SET last_number = GREATEST(shop_sale_counter.last_number, EXCLUDED.last_number);

ALTER TABLE shop_sale ALTER COLUMN sale_number SET NOT NULL;

-- Trigger: asigna el siguiente número de la tienda en cada inserción
CREATE OR REPLACE FUNCTION shop_sale_assign_number() RETURNS trigger AS $$
BEGIN
    IF NEW.sale_number IS NULL THEN
        INSERT INTO shop_sale_counter (establishment_id, last_number)
        VALUES (NEW.establishment_id, 1)
        ON CONFLICT (establishment_id)
        DO UPDATE SET last_number = shop_sale_counter.last_number + 1
        RETURNING last_number INTO NEW.sale_number;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_shop_sale_assign_number ON shop_sale;
CREATE TRIGGER trg_shop_sale_assign_number
    BEFORE INSERT ON shop_sale
    FOR EACH ROW
    EXECUTE FUNCTION shop_sale_assign_number();