-- public.action_type definition

-- Drop table

-- DROP TABLE public.action_type;

CREATE TABLE public.action_type (
	id int4 DEFAULT nextval('action_type_at_id_seq'::regclass) NOT NULL,
	status int2 NOT NULL,
	"name" varchar(50) NOT NULL,
	"type" varchar(30) NOT NULL,
	unit_name varchar(30) NULL,
	color varchar(7) NULL,
	"action" varchar(10) NULL,
	CONSTRAINT action_type_pkey PRIMARY KEY (id)
);


-- public.payment_type definition

-- Drop table

-- DROP TABLE public.payment_type;

CREATE TABLE public.payment_type (
	id int4 DEFAULT nextval('payment_type_pt_id_seq'::regclass) NOT NULL,
	status int2 NOT NULL,
	"name" varchar(30) NOT NULL,
	CONSTRAINT payment_type_pkey PRIMARY KEY (id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	status int2 NOT NULL,
	"name" varchar(30) NOT NULL,
	paths text NULL,
	CONSTRAINT role_pkey PRIMARY KEY (id)
);


-- public.sql_queries definition

-- Drop table

-- DROP TABLE public.sql_queries;

CREATE TABLE public.sql_queries (
	id serial4 NOT NULL,
	descripcion varchar(500) NULL,
	"path" varchar(100) NULL,
	consulta_sql text NULL,
	principal_table varchar(100) NULL,
	"type" varchar(50) NULL,
	CONSTRAINT sql_queries_pkey PRIMARY KEY (id)
);


-- public.status definition

-- Drop table

-- DROP TABLE public.status;

CREATE TABLE public.status (
	id serial4 NOT NULL,
	status int2 NOT NULL,
	"name" varchar(30) NOT NULL,
	"type" varchar(25) NOT NULL,
	bg_color varchar(7) NULL,
	color varchar(7) NULL,
	CONSTRAINT status_pkey PRIMARY KEY (id)
);


-- public.unit_base definition

-- Drop table

-- DROP TABLE public.unit_base;

CREATE TABLE public.unit_base (
	id serial4 NOT NULL,
	"name" varchar(30) NOT NULL,
	"type" varchar(10) NOT NULL,
	CONSTRAINT unit_base_pkey PRIMARY KEY (id)
);


-- public.measure definition

-- Drop table

-- DROP TABLE public.measure;

CREATE TABLE public.measure (
	id serial4 NOT NULL,
	status int2 NOT NULL,
	"name" varchar(30) NOT NULL,
	unit_base_id int4 NULL,
	unit_base_quantity numeric(8, 5) NOT NULL,
	CONSTRAINT measure_pkey PRIMARY KEY (id),
	CONSTRAINT measure_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES public.unit_base(id)
);


-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	username varchar(50) NOT NULL,
	"password" varchar(255) NULL,
	status_id int4 NOT NULL,
	email varchar(50) NOT NULL,
	phone int4 NULL,
	role_id int4 NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NULL,
	updated_date timestamp NULL,
	external_id varchar(30) NULL,
	CONSTRAINT user_email_key UNIQUE (email),
	CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT user_fk_role_id FOREIGN KEY (role_id) REFERENCES public."role"(id),
	CONSTRAINT user_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.establishment_type definition

CREATE TABLE public.establishment_type (
	id int4 NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT establishment_type_pkey PRIMARY KEY (id)
);


-- public.establishment definition

-- Drop table

-- DROP TABLE public.establishment;

CREATE TABLE public.establishment (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NOT NULL,
	address varchar(50) NOT NULL,
	description text NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	receive_pending_orders_enabled bool DEFAULT false NOT NULL,
	establishment_type_id int4 NOT NULL DEFAULT 1,
	CONSTRAINT establishment_pkey PRIMARY KEY (id),
	CONSTRAINT finished_product_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT finished_product_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id),
	CONSTRAINT establishment_fk_type_id FOREIGN KEY (establishment_type_id) REFERENCES public.establishment_type(id)
);

-- Migration: ALTER TABLE public.establishment ADD COLUMN receive_pending_orders_enabled bool DEFAULT false NOT NULL;
-- Migration: CREATE TABLE public.establishment_type (id int4 NOT NULL, "name" varchar(50) NOT NULL, CONSTRAINT establishment_type_pkey PRIMARY KEY (id));
-- Migration: INSERT INTO public.establishment_type (id, name) VALUES (1, 'producto'), (2, 'abarrote');
-- Migration: ALTER TABLE public.establishment ADD COLUMN establishment_type_id int4 NOT NULL DEFAULT 1;
-- Migration: ALTER TABLE public.establishment ADD CONSTRAINT establishment_fk_type_id FOREIGN KEY (establishment_type_id) REFERENCES public.establishment_type(id);


-- public.finished_product_type definition

CREATE TABLE public.finished_product_type (
	id int4 NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT finished_product_type_pkey PRIMARY KEY (id)
);


-- public.finished_product definition

-- Drop table

-- DROP TABLE public.finished_product;

CREATE TABLE public.finished_product (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NOT NULL,
	description varchar(200) NULL,
	photo text NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	unit_base_id int4 NOT NULL,
	finished_product_type_id int4 NOT NULL DEFAULT 1,
	CONSTRAINT finished_product_pkey PRIMARY KEY (id),
	CONSTRAINT finished_product_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT finished_product_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id),
	CONSTRAINT finished_product_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES public.unit_base(id),
	CONSTRAINT finished_product_fk_type_id FOREIGN KEY (finished_product_type_id) REFERENCES public.finished_product_type(id)
);

-- Migration:
-- CREATE TABLE public.finished_product_type (id int4 NOT NULL, "name" varchar(50) NOT NULL, CONSTRAINT finished_product_type_pkey PRIMARY KEY (id));
-- INSERT INTO public.finished_product_type (id, name) VALUES (1, 'embutido'), (2, 'abarrote');
-- ALTER TABLE public.finished_product ADD COLUMN finished_product_type_id int4 NOT NULL DEFAULT 1;
-- ALTER TABLE public.finished_product ADD CONSTRAINT finished_product_fk_type_id FOREIGN KEY (finished_product_type_id) REFERENCES public.finished_product_type(id);


-- public.inventory definition

-- Drop table

-- DROP TABLE public.inventory;

CREATE TABLE public.inventory (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(150) NOT NULL,
	description varchar(50) NULL,
	person_in_charge_id uuid NOT NULL,
	inventory_type varchar(25) NOT NULL,
	unit_name varchar(150) NOT NULL,
	status_id int4 DEFAULT 48 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (id),
	CONSTRAINT inventory_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT inventory_fk_person_in_charge_id FOREIGN KEY (person_in_charge_id) REFERENCES public."user"(id),
	CONSTRAINT inventory_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.inventory_element definition

-- Drop table

-- DROP TABLE public.inventory_element;

CREATE TABLE public.inventory_element (
	id int4 DEFAULT nextval('inventory_element_ie_id_seq'::regclass) NOT NULL,
	inventory_id uuid NOT NULL,
	element_type varchar(20) NOT NULL,
	element_table varchar(100) NOT NULL,
	establishment_id uuid NULL,
	measure_id int4 NULL,
	quantity numeric(12, 5) NOT NULL,
	status_id int4 DEFAULT 48 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	element_fk uuid NOT NULL,
	CONSTRAINT inventory_element_pkey PRIMARY KEY (id),
	CONSTRAINT inventory_element_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT inventory_element_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES public.establishment(id),
	CONSTRAINT inventory_element_fk_inventory_id FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
	CONSTRAINT inventory_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT inventory_element_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.inventory_element_action definition

-- Drop table

-- DROP TABLE public.inventory_element_action;

CREATE TABLE public.inventory_element_action (
	id int4 DEFAULT nextval('inventory_element_action_iem_id_seq'::regclass) NOT NULL,
	"comment" varchar(255) NULL,
	source_inventory_element_id int4 NOT NULL,
	target_inventory_element_id int4 NULL,
	quantity numeric(12, 5) NOT NULL,
	measure_id int4 NOT NULL,
	action_type_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	CONSTRAINT inventory_element_action_pkey PRIMARY KEY (id),
	CONSTRAINT inventory_element_action_fk_action_type_id FOREIGN KEY (action_type_id) REFERENCES public.action_type(id),
	CONSTRAINT inventory_element_action_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT inventory_element_action_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT inventory_element_action_fk_source_inventory_element_id FOREIGN KEY (source_inventory_element_id) REFERENCES public.inventory_element(id),
	CONSTRAINT inventory_element_action_fk_target_inventory_element_id FOREIGN KEY (target_inventory_element_id) REFERENCES public.inventory_element(id)
);


-- public.product_for_sale definition

-- Drop table

-- DROP TABLE public.product_for_sale;

CREATE TABLE public.product_for_sale (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	price numeric(10, 2) NOT NULL,
	establishment_id uuid NOT NULL,
	finished_product_id uuid NOT NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT product_for_sale_pkey PRIMARY KEY (id),
	CONSTRAINT product_for_sale_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT product_for_sale_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES public.establishment(id),
	CONSTRAINT product_for_sale_fk_finished_product_id FOREIGN KEY (finished_product_id) REFERENCES public.finished_product(id),
	CONSTRAINT product_for_sale_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.product_for_sale_store_order definition

-- Drop table

-- DROP TABLE public.product_for_sale_store_order;

CREATE TABLE public.product_for_sale_store_order (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NULL,
	"comment" text NULL,
	establishment_id uuid NOT NULL,
	inventory_id uuid NULL,
	final_amount numeric(10, 2) NOT NULL,
	factory_status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	store_status_id int4 NOT NULL,
	CONSTRAINT product_for_sale_store_order_pkey PRIMARY KEY (id),
	CONSTRAINT product_for_sale_store_order_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT product_for_sale_store_order_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES public.establishment(id),
	CONSTRAINT product_for_sale_store_order_fk_factory_status_id FOREIGN KEY (factory_status_id) REFERENCES public.status(id),
	CONSTRAINT product_for_sale_store_order_fk_inventory_id FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
	CONSTRAINT product_for_sale_store_order_status_fk FOREIGN KEY (store_status_id) REFERENCES public.status(id)
);


-- public.product_for_sale_store_order_element definition

-- Drop table

-- DROP TABLE public.product_for_sale_store_order_element;

CREATE TABLE public.product_for_sale_store_order_element (
	id int4 DEFAULT nextval('product_for_sale_store_order_element_pfssoe_id_seq'::regclass) NOT NULL,
	product_for_sale_id uuid NOT NULL,
	quantity numeric(12, 5) NOT NULL,
	measure_id int4 NOT NULL,
	price numeric(10, 2) NOT NULL,
	total_price numeric(10, 2) NOT NULL,
	"date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	pfsso_id uuid NOT NULL,
	CONSTRAINT product_for_sale_store_order_element_pkey PRIMARY KEY (id),
	CONSTRAINT product_for_sale_store_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT product_for_sale_store_order_element_fk_product_for_sale_id FOREIGN KEY (product_for_sale_id) REFERENCES public.product_for_sale(id),
	CONSTRAINT product_for_sale_store_order_element_product_for_sale_store_ord FOREIGN KEY (pfsso_id) REFERENCES public.product_for_sale_store_order(id)
);


-- public.provider definition

-- Drop table

-- DROP TABLE public.provider;

CREATE TABLE public.provider (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NOT NULL,
	phone int4 NULL,
	description varchar(255) NULL,
	company varchar(50) NOT NULL,
	email varchar(100) NOT NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT provider_email_key UNIQUE (email),
	CONSTRAINT provider_pkey PRIMARY KEY (id),
	CONSTRAINT provider_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT provider_fk_sttus_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.raw_material definition

-- Drop table

-- DROP TABLE public.raw_material;

CREATE TABLE public.raw_material (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NOT NULL,
	description varchar(255) NULL,
	photo text NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	unit_base_id int4 NOT NULL,
	CONSTRAINT raw_material_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT raw_material_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id),
	CONSTRAINT raw_material_fk_unit_base_id FOREIGN KEY (unit_base_id) REFERENCES public.unit_base(id)
);


-- public.raw_material_by_provider_type definition

CREATE TABLE public.raw_material_by_provider_type (
	id int4 NOT NULL,
	"name" varchar(50) NOT NULL,
	CONSTRAINT raw_material_by_provider_type_pkey PRIMARY KEY (id)
);
-- Migration: INSERT INTO public.raw_material_by_provider_type (id, "name") VALUES (1, 'alimento'), (2, 'empaque');

-- public.raw_material_by_provider definition

-- Drop table

-- DROP TABLE public.raw_material_by_provider;

CREATE TABLE public.raw_material_by_provider (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	price numeric(10, 2) NOT NULL,
	provider_id uuid NOT NULL,
	raw_material_base_id uuid NOT NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	raw_material_by_provider_type_id int4 NOT NULL DEFAULT 1,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT raw_material_by_provider_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_by_provider_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT raw_material_by_provider_fk_provider_id FOREIGN KEY (provider_id) REFERENCES public.provider(id),
	CONSTRAINT raw_material_by_provider_fk_raw_material_base_id FOREIGN KEY (raw_material_base_id) REFERENCES public.raw_material(id),
	CONSTRAINT raw_material_by_provider_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id),
	CONSTRAINT raw_material_by_provider_fk_type_id FOREIGN KEY (raw_material_by_provider_type_id) REFERENCES public.raw_material_by_provider_type(id)
);
-- Migration: ALTER TABLE public.raw_material_by_provider ADD COLUMN raw_material_by_provider_type_id int4 NOT NULL DEFAULT 1;
-- Migration: ALTER TABLE public.raw_material_by_provider ADD CONSTRAINT raw_material_by_provider_fk_type_id FOREIGN KEY (raw_material_by_provider_type_id) REFERENCES public.raw_material_by_provider_type(id);


-- public.raw_material_order definition

-- Drop table

-- DROP TABLE public.raw_material_order;

CREATE TABLE public.raw_material_order (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(50) NOT NULL,
	description varchar(100) NULL,
	provider_id uuid NOT NULL,
	payment_type_id int4 NOT NULL,
	pending_amount numeric(10, 2) NOT NULL,
	paid_amount numeric(10, 2) NOT NULL,
	final_amount numeric(10, 2) NOT NULL,
	payment_status_id int4 NOT NULL,
	status_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT raw_material_order_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_order_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT raw_material_order_fk_payment_status_id FOREIGN KEY (payment_status_id) REFERENCES public.status(id),
	CONSTRAINT raw_material_order_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES public.payment_type(id),
	CONSTRAINT raw_material_order_fk_provider_id FOREIGN KEY (provider_id) REFERENCES public.provider(id),
	CONSTRAINT raw_material_order_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.raw_material_order_element definition

-- Drop table

-- DROP TABLE public.raw_material_order_element;

CREATE TABLE public.raw_material_order_element (
	id int4 DEFAULT nextval('raw_material_order_element_pmoe_id_seq'::regclass) NOT NULL,
	raw_material_order_id uuid NOT NULL,
	raw_material_by_provider_id uuid NOT NULL,
	quantity numeric(12, 5) NOT NULL,
	discount numeric(10, 2) NOT NULL,
	measure_id int4 NOT NULL,
	price numeric(10, 2) NOT NULL,
	subtotal_price numeric(10, 2) NOT NULL,
	total_discount numeric(10, 2) NOT NULL,
	total_price numeric(10, 2) NOT NULL,
	"date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	CONSTRAINT raw_material_order_element_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT raw_material_order_element_fk_raw_material_by_provider_id FOREIGN KEY (raw_material_by_provider_id) REFERENCES public.raw_material_by_provider(id),
	CONSTRAINT raw_material_order_element_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES public.raw_material_order(id)
);


-- public.raw_material_order_element_aux definition

-- Drop table

-- DROP TABLE public.raw_material_order_element_aux;

CREATE TABLE public.raw_material_order_element_aux (
	id int4 DEFAULT nextval('raw_material_order_element_aux_pmoe_id_seq'::regclass) NOT NULL,
	raw_material_order_id uuid NOT NULL,
	raw_material_by_provider_id uuid NOT NULL,
	quantity numeric(8, 5) NOT NULL,
	discount numeric(10, 2) NOT NULL,
	measure_id int4 NOT NULL,
	price numeric(10, 2) NOT NULL,
	subtotal_price numeric(10, 2) NOT NULL,
	total_discount numeric(10, 2) NOT NULL,
	total_price numeric(10, 2) NOT NULL,
	"date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	CONSTRAINT raw_material_order_element_aux_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_order_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT raw_material_order_element_fk_raw_material_by_provider_id FOREIGN KEY (raw_material_by_provider_id) REFERENCES public.raw_material_by_provider(id),
	CONSTRAINT raw_material_order_element_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES public.raw_material_order(id)
);


-- public.raw_material_order_payment definition

-- Drop table

-- DROP TABLE public.raw_material_order_payment;

CREATE TABLE public.raw_material_order_payment (
	id int4 DEFAULT nextval('raw_material_order_payment_pmop_id_seq'::regclass) NOT NULL,
	raw_material_order_id uuid NOT NULL,
	amount numeric(10, 2) NOT NULL,
	payment_type_id int4 NOT NULL,
	"date" timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	CONSTRAINT raw_material_order_payment_pkey PRIMARY KEY (id),
	CONSTRAINT raw_material_order_payment_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES public.payment_type(id),
	CONSTRAINT raw_material_order_payment_fk_raw_material_order_id FOREIGN KEY (raw_material_order_id) REFERENCES public.raw_material_order(id)
);


-- public.shop_sale definition

-- Drop table

-- DROP TABLE public.shop_sale;

CREATE TABLE public.shop_sale (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	name_client varchar(50) NOT NULL,
	nota varchar(100) NOT NULL,
	delivery numeric(10, 2) DEFAULT 0 NULL,
	nit_client varchar(10) DEFAULT 'CF'::character varying NULL,
	establishment_id uuid NOT NULL,
	status_id int4 NOT NULL,
	total numeric(10, 2) NOT NULL,
	total_discount numeric(10, 2) NOT NULL,
	payment_type_id int4 NOT NULL,
	creator_user_id uuid NOT NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	CONSTRAINT shop_sale_pkey PRIMARY KEY (id),
	CONSTRAINT shop_sale_fk_creator_user_id FOREIGN KEY (creator_user_id) REFERENCES public."user"(id),
	CONSTRAINT shop_sale_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES public.establishment(id),
	CONSTRAINT shop_sale_fk_payment_type_id FOREIGN KEY (payment_type_id) REFERENCES public.payment_type(id),
	CONSTRAINT shop_sale_fk_status_id FOREIGN KEY (status_id) REFERENCES public.status(id)
);


-- public.shop_sale_element definition

-- Drop table

-- DROP TABLE public.shop_sale_element;

CREATE TABLE public.shop_sale_element (
	id int4 DEFAULT nextval('shop_sale_element_sse_id_seq'::regclass) NOT NULL,
	shop_sale_id uuid NOT NULL,
	product_for_sale_id uuid NOT NULL,
	price numeric(10, 2) NOT NULL,
	subtotal numeric(10, 2) NOT NULL,
	total numeric(10, 2) NOT NULL,
	discount numeric(10, 2) NOT NULL,
	total_discount numeric(10, 2) NOT NULL,
	quantity numeric(12, 5) NOT NULL,
	measure_id int4 NULL,
	CONSTRAINT shop_sale_element_pkey PRIMARY KEY (id),
	CONSTRAINT shop_sale_element_fk_measure_id FOREIGN KEY (measure_id) REFERENCES public.measure(id),
	CONSTRAINT shop_sale_element_fk_product_for_sale_id FOREIGN KEY (product_for_sale_id) REFERENCES public.product_for_sale(id),
	CONSTRAINT shop_sale_element_fk_shop_sale_id FOREIGN KEY (shop_sale_id) REFERENCES public.shop_sale(id)
);


-- public.cash_closing definition

-- Drop table

-- DROP TABLE public.cash_closing;

CREATE TABLE public.cash_closing (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	establishment_id uuid NOT NULL,
	status_id int4 NOT NULL,
	shop_sales jsonb NULL,
	last_inventory_capture jsonb NULL,
	last_inventory_creation_date timestamp NULL,
	inventory_capture jsonb NULL,
	inventory_element_actions jsonb NULL,
	validator_user uuid NOT NULL,
	confirm_user uuid NULL,
	creation_date timestamp DEFAULT timezone('UTC'::text, CURRENT_TIMESTAMP) NOT NULL,
	updated_date timestamp NULL,
	note text NULL,
	sale_store_orders jsonb NULL,
	CONSTRAINT cash_closing_pkey PRIMARY KEY (id),
	CONSTRAINT cash_closing_fk_confirm_user FOREIGN KEY (confirm_user) REFERENCES public."user"(id),
	CONSTRAINT cash_closing_fk_establishment_id FOREIGN KEY (establishment_id) REFERENCES public.establishment(id),
	CONSTRAINT cash_closing_fk_sttus_id FOREIGN KEY (status_id) REFERENCES public.status(id),
	CONSTRAINT cash_closing_fk_validator_user FOREIGN KEY (validator_user) REFERENCES public."user"(id)
);